### ISSUE TITLE
Using a database name that doesn't require wrapping in quotes 

### ISSUE THREAD

**Issue by narendasan** [HackIllinois/api-2017#33]
hackillinois-2017 makes sense for our naming conventions but makes things painful for the user to setup. Both flyway and mysql get mad about having the db named hackillinois-2017 and while I could get around the issues in mysql, flyway took more time than I wanted to spend so currently I am using a db named hackillinois. 

Personally I think that there are 2 options here:
1. use a more complacent db name
2. add documentation on how to get around it. 

If the answer is path 2, the flyway script needs to be updated to better handle the db name because I get an error right now

**Comment by narendasan** [comment]
The issue may stem from versions of MySQL, I am just using the one provided through brew

**Comment by nmagerko** [comment]
Flyway is giving you trouble because of the datastore name? I haven't had any issues. The script should take care of everything that you need if you use the name that is documented in the README (that's the reason it's there: to make things less painful). If there's an error, please post it so that we can get it resolved.

Everything will probably be renamed as this evolves (eventually I see this project not being called `api-2017` or even having explicit references to `hackillinois`, because who really wants to use that). In the meantime, I don't think typing two backticks once to create the table is really that painful.

**Comment by nmagerko** [comment]
I think a standing issue about re-branding the project is more reasonable than just re-naming the datastore at this point. Unless there is an issue with the migration script, I do not believe this is worth tweaking now.

**Comment by nmagerko** [comment]
Closing in favor of the more flexible approach of just changing the default name in a configuration template (see #32)
